Homework 3
Ole-Leo/skypro-react pull request #3
Opened 2022-06-01 11:12 UTC by Ole-Leo

#### Задание урок 5.3 Компонент
На базе\примере компонентов урока, сделайте компонент, который:
Принимает параметры **min** и **max**.
В состоянии хранит текущее значение счётчика - **curCount**.
Задает изначальное значение **curCount**= min.
Содержит кнопки для увеличения и уменьшения **curCount** на 1.
Не позволяет значению **curCount** выходить за границы **min** и **max**.
Выводит **curCount** в между двумя кнопками.
Вместо между кнопками расположить **input[type=text]**\*. Число в этом input синхронизируется с **curCount**. 

*(помните, что человек может ввести в поле любую текстовую бессмыслицу)

2022-06-02 15:20 UTC, mrerberg requested changes

2022-06-02 15:20 UTC, mrerberg commented on skypro-react/src/homework_3/CounterWithInput.js
> +    this.state.current = inputValue.replace(/\D/gi, '');
Стейт нельзя менять напрямую, только через функцию setState

2022-06-02 17:29 UTC, Ole-Leo commented on skypro-react/src/homework_3/CounterWithInput.js
> +    this.state.current = inputValue.replace(/\D/gi, '');
Поменяла:
```js
this.setState({ current: inputValue });
```

2022-06-03 07:52 UTC, mrerberg requested changes

2022-06-03 07:52 UTC, mrerberg commented on skypro-react/src/homework_3/CounterWithInput.js
> +    this.setState({ current: inputValue });
Зачем дважды делать в функции `this.setState`? Сделай 1 раз в конце функции, а до этого определи значение inputValue.

```
let inputValue = event.target.value.replace(/\D/gi, '');

if (inputValue > max) inputValue = max;
    if (inputValue < min) inputValue = min;
    this.setState(() => ({ current: inputValue }));
```

2022-06-03 14:38 UTC, Ole-Leo commented on skypro-react/src/homework_3/CounterWithInput.js
> +    this.setState({ current: inputValue });
Я с этими стейтами окончательно запуталась :/
Когда нужно использовать prevState? Можно ли просто сделать setState = ({новое значение})?
В общем, ничего не понятно, но очень интересно)

Спасибо за корректировку, поменяла)
```js
 onChange(event) {
    let inputValue = event.target.value.replace(/\D/gi, '');
    if (inputValue > max) inputValue = max;
    if (inputValue < min) inputValue = min;
    this.setState(() => ({ current: inputValue }));
  }
 ```

2022-06-05 08:57 UTC, mrerberg approved these changes

2022-06-05 13:16 UTC, merged