init: homework_4-tasks
Ole-Leo/skypro-react pull request #5
Opened 2022-06-09 12:43 UTC by Ole-Leo

1. **Используя скелет компоненты, допишите код таймера до рабочего** 
   * Исправьте ошибки.
   * В методах жизненных циклов определите взаимодействие с состоянием.
   * Повесьте события на кнопки. Допишите хендлеры.

```jsx
import React from 'react';
import './styles.css';

export default class ReacTimer extends React.Component {
    state = {
        count: 0,
        isCounting: false,
    };

    componentDidMount() {}

    componentDidUpdate() {}

    componentWillUnmount() {}

    render() {
        return (
            <div className="ReacTimer">
                <h1>React Timer</h1>
                <h3>{this.state.count}</h3>
                {!this.state.isCounting ? (
                    <button onClick={this.handleStart}>Start</button>
                ) : (
                    <button onClick={this.handleStop}>Stop</button>
                )}
                <button onClick={this.handleReset}>Reset</button>
            </div>
        );
    }
}
```

2. **Написать классовый компонент Часы**
- Часы должны отображать реальное время и обновляться каждую секунду.
- Используйте методы жизненного цикла.
- Не забудьте очистить компонент перед размонтированием.

3. ⭐ **Написать компонент Pomodoro Tracker** (задача со звездочкой)

Компонент из 3х кнопок и отображения обратного отсчёта:
* Work Time - запускает таймер обратного отсчёта на 30 мин.
* Long Break - запускает таймер обратного отсчёта на 15 мин.
* Short Break - запускает таймер обратного отсчёта на 7 мин.

![image](https://user-images.githubusercontent.com/95646471/172849537-b90b8225-a679-4a5e-a92f-6913d12efe9a.png)

2022-06-10 09:39 UTC, mrerberg requested changes

2022-06-10 09:39 UTC, mrerberg commented on skypro-react/src/homework_4/PomodoroTracker.js
> +    if (targetAttr === 'work') {
Может все это заменить на 

```
this.setState({ counter: tracker[targetAttr], isCounting: true });
```

?

2022-06-10 16:22 UTC, Ole-Leo commented on skypro-react/src/homework_4/PomodoroTracker.js
> +    if (targetAttr === 'work') {
Вообще огонь! поменяла)
Я думала о чём-то подобном, но у меня не получилось :/

2022-06-11 14:39 UTC, mrerberg approved these changes

2022-06-11 16:02 UTC, merged